### PR TITLE
macOS X Support

### PR DESCRIPTION
**Pull request by ghulands**
I have successfully run goesrecv, but as yet haven't got any LRIT data as I'm still waiting for my LNA to arrive.

### CODE REVIEW

**Comment by pietern** [comment]
Thank you! Very cool to hear you got it working on macOS.

Unfortunately I don't have macOS CI setup so I can't guarantee I won't break it in the future. Could you try and see if you can add the "airspy" and "rtlsdr" names after the existing `NAMES` argument in `find_library`? Then it will be a bit simpler compared to branching on the system name.

**Comment by ghulands** [comment]
Done. Builds fine.

**Comment by pietern** [comment]
Many thanks!

**Comment by pietern** [comment]
@ghulands What is your antenna setup? Hope you get the LNA soon and can start receiving :)

**Pull request merged**
